{{- if .Values.serviceAccount.create -}}
---
# configure the service account with attached IAM role
apiVersion: v1
kind: ServiceAccount
metadata:
  name: adot-collector
  namespace: {{ .Values.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: {{ required "A valid .Values.serviceAccount.iamRoleArn entry required!" .Values.serviceAccount.iamRoleArn }}
---
{{- end -}}
